[package]
name = "solina-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"
service = "0.0.0"
tokio = { version = "1.32.0", features = ["full"] }
solina = { path = "../solina/" }
num-bigint = { version = "0.4.3", features = ["serde"] }
keccak-hash = "0.10.0"
serde = { version = "1.0.185", features = ["derive"] }
thiserror = "1.0.47"
bincode = "1.3.3"
storage-sqlite = { path = "../storage_sqlite/" }
