[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "1.0.0-rc.2"

[dependencies]
risc0-zkvm = { version = "1.0.0-rc.2", default-features = false, features = ["std"] }

[profile.release]
lto = true
opt-level = 3

[package.metadata.risc0]
methods = ["guest"]

[patch.crates-io]
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "d02f606ab7d59ad45dc75314eb3e0eef5c9a26b7"}
risc0-build = { git = "https://github.com/risc0/risc0", rev = "d02f606ab7d59ad45dc75314eb3e0eef5c9a26b7"}