[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "1.0.0-rc.2"

[dependencies]
risc0-zkvm = { version = "1.0.0-rc.2", default-features = false, features = ["std"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
anyhow = "1.0"

[profile.release]
lto = true
opt-level = 3
